name: Build and Lint Next.js App

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./drep-id-inspector

      - name: Run linter
        run: npm run lint
        working-directory: ./drep-id-inspector

      - name: Build application
        run: npm run build
        working-directory: ./drep-id-inspector